// Generated by jextract

package oracle.code.onnx.coreml.foreign;

/**
 * {@snippet lang=c :
 * typedef struct _opaque_pthread_rwlockattr_t {
 *     long __sig;
 *     char __opaque[16];
 * } __darwin_pthread_rwlockattr_t
 * }
 */
public class __darwin_pthread_rwlockattr_t extends _opaque_pthread_rwlockattr_t {

    __darwin_pthread_rwlockattr_t() {
        // Should not be called directly
    }
}

