// Generated by jextract

package oracle.code.onnx.coreml.foreign;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef OrtStatus *(*OrtGetInitializerLocationFunc)(void *, const char *, const OrtValue *, const OrtExternalInitializerInfo *, OrtExternalInitializerInfo **)
 * }
 */
public class OrtGetInitializerLocationFunc {

    OrtGetInitializerLocationFunc() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment state, MemorySegment initializer_name, MemorySegment initializer_value, MemorySegment external_info, MemorySegment new_external_info);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        coreml_provider_factory_h.C_POINTER,
        coreml_provider_factory_h.C_POINTER,
        coreml_provider_factory_h.C_POINTER,
        coreml_provider_factory_h.C_POINTER,
        coreml_provider_factory_h.C_POINTER,
        coreml_provider_factory_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = coreml_provider_factory_h.upcallHandle(Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment state, MemorySegment initializer_name, MemorySegment initializer_value, MemorySegment external_info, MemorySegment new_external_info) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, state, initializer_name, initializer_value, external_info, new_external_info);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

