// Generated by jextract

package oracle.code.onnx.coreml.foreign;

/**
 * {@snippet lang=c :
 * typedef __darwin_pthread_attr_t pthread_attr_t
 * }
 */
public class pthread_attr_t extends _opaque_pthread_attr_t {

    pthread_attr_t() {
        // Should not be called directly
    }
}

