// Generated by jextract

package oracle.code.onnx.coreml.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sigstack {
 *     char *ss_sp;
 *     int ss_onstack;
 * }
 * }
 */
public class sigstack {

    sigstack() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        coreml_provider_factory_h.C_POINTER.withName("ss_sp"),
        coreml_provider_factory_h.C_INT.withName("ss_onstack"),
        MemoryLayout.paddingLayout(4)
    ).withName("sigstack");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout ss_sp$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ss_sp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *ss_sp
     * }
     */
    public static final AddressLayout ss_sp$layout() {
        return ss_sp$LAYOUT;
    }

    private static final long ss_sp$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *ss_sp
     * }
     */
    public static final long ss_sp$offset() {
        return ss_sp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *ss_sp
     * }
     */
    public static MemorySegment ss_sp(MemorySegment struct) {
        return struct.get(ss_sp$LAYOUT, ss_sp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *ss_sp
     * }
     */
    public static void ss_sp(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ss_sp$LAYOUT, ss_sp$OFFSET, fieldValue);
    }

    private static final OfInt ss_onstack$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ss_onstack"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ss_onstack
     * }
     */
    public static final OfInt ss_onstack$layout() {
        return ss_onstack$LAYOUT;
    }

    private static final long ss_onstack$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ss_onstack
     * }
     */
    public static final long ss_onstack$offset() {
        return ss_onstack$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ss_onstack
     * }
     */
    public static int ss_onstack(MemorySegment struct) {
        return struct.get(ss_onstack$LAYOUT, ss_onstack$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ss_onstack
     * }
     */
    public static void ss_onstack(MemorySegment struct, int fieldValue) {
        struct.set(ss_onstack$LAYOUT, ss_onstack$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

