// Generated by jextract

package oracle.code.onnx.coreml.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sigvec {
 *     void (*sv_handler)(int);
 *     int sv_mask;
 *     int sv_flags;
 * }
 * }
 */
public class sigvec {

    sigvec() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        coreml_provider_factory_h.C_POINTER.withName("sv_handler"),
        coreml_provider_factory_h.C_INT.withName("sv_mask"),
        coreml_provider_factory_h.C_INT.withName("sv_flags")
    ).withName("sigvec");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*sv_handler)(int)
     * }
     */
    public static class sv_handler {

        sv_handler() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(int _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            coreml_provider_factory_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = coreml_provider_factory_h.upcallHandle(sv_handler.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(sv_handler.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,int _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout sv_handler$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sv_handler"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*sv_handler)(int)
     * }
     */
    public static final AddressLayout sv_handler$layout() {
        return sv_handler$LAYOUT;
    }

    private static final long sv_handler$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*sv_handler)(int)
     * }
     */
    public static final long sv_handler$offset() {
        return sv_handler$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*sv_handler)(int)
     * }
     */
    public static MemorySegment sv_handler(MemorySegment struct) {
        return struct.get(sv_handler$LAYOUT, sv_handler$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*sv_handler)(int)
     * }
     */
    public static void sv_handler(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sv_handler$LAYOUT, sv_handler$OFFSET, fieldValue);
    }

    private static final OfInt sv_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sv_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int sv_mask
     * }
     */
    public static final OfInt sv_mask$layout() {
        return sv_mask$LAYOUT;
    }

    private static final long sv_mask$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int sv_mask
     * }
     */
    public static final long sv_mask$offset() {
        return sv_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int sv_mask
     * }
     */
    public static int sv_mask(MemorySegment struct) {
        return struct.get(sv_mask$LAYOUT, sv_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int sv_mask
     * }
     */
    public static void sv_mask(MemorySegment struct, int fieldValue) {
        struct.set(sv_mask$LAYOUT, sv_mask$OFFSET, fieldValue);
    }

    private static final OfInt sv_flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sv_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int sv_flags
     * }
     */
    public static final OfInt sv_flags$layout() {
        return sv_flags$LAYOUT;
    }

    private static final long sv_flags$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int sv_flags
     * }
     */
    public static final long sv_flags$offset() {
        return sv_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int sv_flags
     * }
     */
    public static int sv_flags(MemorySegment struct) {
        return struct.get(sv_flags$LAYOUT, sv_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int sv_flags
     * }
     */
    public static void sv_flags(MemorySegment struct, int fieldValue) {
        struct.set(sv_flags$LAYOUT, sv_flags$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

