/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package jdk.incubator.code.bytecode.impl;

import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassTransform;

/**
 * Applies bytecode compaction passes to a generated class file.
 * <p>
 * The generated bytes are parsed first so all compactors work from the final
 * class-file model, including complete code attributes, stack maps and
 * exception tables.
 */
public class BytecodeCompactor {

    /**
     * Parses and compacts generated class bytes.
     *
     * @param classBytes generated class bytes
     * @return compacted class bytes
     */
    public static byte[] transform(byte[] classBytes) {
        return ClassFile.of().transformClass(ClassFile.of().parse(classBytes),
                LocalsCompactor.instance().andThen(ClassTransform.transformingMethodBodies(
                        new ExceptionTableCompactor().andThen(
                                new BranchCompactor()))));
    }

}
