// Generated by jextract

package oracle.code.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtExternalResourceImporterImpl {
 *     uint32_t ort_version_supported;
 *     bool (*CanImportMemory)(const OrtExternalResourceImporterImpl *, OrtExternalMemoryHandleType);
 *     OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **);
 *     void (*ReleaseMemory)(OrtExternalResourceImporterImpl *, OrtExternalMemoryHandle *);
 *     OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **);
 *     bool (*CanImportSemaphore)(const OrtExternalResourceImporterImpl *, OrtExternalSemaphoreType);
 *     OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporterImpl *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **);
 *     void (*ReleaseSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *);
 *     OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t);
 *     OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t);
 *     void (*Release)(OrtExternalResourceImporterImpl *);
 * }
 * }
 */
public class OrtExternalResourceImporterImpl {

    OrtExternalResourceImporterImpl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("ort_version_supported"),
        MemoryLayout.paddingLayout(4),
        onnxruntime_c_api_h.C_POINTER.withName("CanImportMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("ImportMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("ReleaseMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("CreateTensorFromMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("CanImportSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("ImportSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("ReleaseSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("WaitSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("SignalSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("Release")
    ).withName("OrtExternalResourceImporterImpl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ort_version_supported$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ort_version_supported"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final OfInt ort_version_supported$layout() {
        return ort_version_supported$LAYOUT;
    }

    private static final long ort_version_supported$OFFSET = $LAYOUT.byteOffset(groupElement("ort_version_supported"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final long ort_version_supported$offset() {
        return ort_version_supported$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static int ort_version_supported(MemorySegment struct) {
        return struct.get(ort_version_supported$LAYOUT, ort_version_supported$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static void ort_version_supported(MemorySegment struct, int fieldValue) {
        struct.set(ort_version_supported$LAYOUT, ort_version_supported$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*CanImportMemory)(const OrtExternalResourceImporterImpl *, OrtExternalMemoryHandleType)
     * }
     */
    public final static class CanImportMemory {

        private CanImportMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_BOOL,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CanImportMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CanImportMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CanImportMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CanImportMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*CanImportMemory)(const OrtExternalResourceImporterImpl *, OrtExternalMemoryHandleType)
     * }
     */
    public static final AddressLayout CanImportMemory$layout() {
        return CanImportMemory$LAYOUT;
    }

    private static final long CanImportMemory$OFFSET = $LAYOUT.byteOffset(groupElement("CanImportMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*CanImportMemory)(const OrtExternalResourceImporterImpl *, OrtExternalMemoryHandleType)
     * }
     */
    public static final long CanImportMemory$offset() {
        return CanImportMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*CanImportMemory)(const OrtExternalResourceImporterImpl *, OrtExternalMemoryHandleType)
     * }
     */
    public static MemorySegment CanImportMemory(MemorySegment struct) {
        return struct.get(CanImportMemory$LAYOUT, CanImportMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*CanImportMemory)(const OrtExternalResourceImporterImpl *, OrtExternalMemoryHandleType)
     * }
     */
    public static void CanImportMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CanImportMemory$LAYOUT, CanImportMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public final static class ImportMemory {

        private ImportMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ImportMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ImportMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ImportMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ImportMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static final AddressLayout ImportMemory$layout() {
        return ImportMemory$LAYOUT;
    }

    private static final long ImportMemory$OFFSET = $LAYOUT.byteOffset(groupElement("ImportMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static final long ImportMemory$offset() {
        return ImportMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static MemorySegment ImportMemory(MemorySegment struct) {
        return struct.get(ImportMemory$LAYOUT, ImportMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static void ImportMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ImportMemory$LAYOUT, ImportMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*ReleaseMemory)(OrtExternalResourceImporterImpl *, OrtExternalMemoryHandle *)
     * }
     */
    public final static class ReleaseMemory {

        private ReleaseMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ReleaseMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ReleaseMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ReleaseMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ReleaseMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*ReleaseMemory)(OrtExternalResourceImporterImpl *, OrtExternalMemoryHandle *)
     * }
     */
    public static final AddressLayout ReleaseMemory$layout() {
        return ReleaseMemory$LAYOUT;
    }

    private static final long ReleaseMemory$OFFSET = $LAYOUT.byteOffset(groupElement("ReleaseMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*ReleaseMemory)(OrtExternalResourceImporterImpl *, OrtExternalMemoryHandle *)
     * }
     */
    public static final long ReleaseMemory$offset() {
        return ReleaseMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*ReleaseMemory)(OrtExternalResourceImporterImpl *, OrtExternalMemoryHandle *)
     * }
     */
    public static MemorySegment ReleaseMemory(MemorySegment struct) {
        return struct.get(ReleaseMemory$LAYOUT, ReleaseMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*ReleaseMemory)(OrtExternalResourceImporterImpl *, OrtExternalMemoryHandle *)
     * }
     */
    public static void ReleaseMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ReleaseMemory$LAYOUT, ReleaseMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public final static class CreateTensorFromMemory {

        private CreateTensorFromMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CreateTensorFromMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CreateTensorFromMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CreateTensorFromMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CreateTensorFromMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static final AddressLayout CreateTensorFromMemory$layout() {
        return CreateTensorFromMemory$LAYOUT;
    }

    private static final long CreateTensorFromMemory$OFFSET = $LAYOUT.byteOffset(groupElement("CreateTensorFromMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static final long CreateTensorFromMemory$offset() {
        return CreateTensorFromMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static MemorySegment CreateTensorFromMemory(MemorySegment struct) {
        return struct.get(CreateTensorFromMemory$LAYOUT, CreateTensorFromMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporterImpl *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static void CreateTensorFromMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CreateTensorFromMemory$LAYOUT, CreateTensorFromMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*CanImportSemaphore)(const OrtExternalResourceImporterImpl *, OrtExternalSemaphoreType)
     * }
     */
    public final static class CanImportSemaphore {

        private CanImportSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_BOOL,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CanImportSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CanImportSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CanImportSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CanImportSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*CanImportSemaphore)(const OrtExternalResourceImporterImpl *, OrtExternalSemaphoreType)
     * }
     */
    public static final AddressLayout CanImportSemaphore$layout() {
        return CanImportSemaphore$LAYOUT;
    }

    private static final long CanImportSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("CanImportSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*CanImportSemaphore)(const OrtExternalResourceImporterImpl *, OrtExternalSemaphoreType)
     * }
     */
    public static final long CanImportSemaphore$offset() {
        return CanImportSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*CanImportSemaphore)(const OrtExternalResourceImporterImpl *, OrtExternalSemaphoreType)
     * }
     */
    public static MemorySegment CanImportSemaphore(MemorySegment struct) {
        return struct.get(CanImportSemaphore$LAYOUT, CanImportSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*CanImportSemaphore)(const OrtExternalResourceImporterImpl *, OrtExternalSemaphoreType)
     * }
     */
    public static void CanImportSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CanImportSemaphore$LAYOUT, CanImportSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporterImpl *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public final static class ImportSemaphore {

        private ImportSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ImportSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ImportSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ImportSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ImportSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporterImpl *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static final AddressLayout ImportSemaphore$layout() {
        return ImportSemaphore$LAYOUT;
    }

    private static final long ImportSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("ImportSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporterImpl *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static final long ImportSemaphore$offset() {
        return ImportSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporterImpl *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static MemorySegment ImportSemaphore(MemorySegment struct) {
        return struct.get(ImportSemaphore$LAYOUT, ImportSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporterImpl *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static void ImportSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ImportSemaphore$LAYOUT, ImportSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*ReleaseSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *)
     * }
     */
    public final static class ReleaseSemaphore {

        private ReleaseSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ReleaseSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ReleaseSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ReleaseSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ReleaseSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*ReleaseSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *)
     * }
     */
    public static final AddressLayout ReleaseSemaphore$layout() {
        return ReleaseSemaphore$LAYOUT;
    }

    private static final long ReleaseSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("ReleaseSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*ReleaseSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *)
     * }
     */
    public static final long ReleaseSemaphore$offset() {
        return ReleaseSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*ReleaseSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *)
     * }
     */
    public static MemorySegment ReleaseSemaphore(MemorySegment struct) {
        return struct.get(ReleaseSemaphore$LAYOUT, ReleaseSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*ReleaseSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *)
     * }
     */
    public static void ReleaseSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ReleaseSemaphore$LAYOUT, ReleaseSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public final static class WaitSemaphore {

        private WaitSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(WaitSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(WaitSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout WaitSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("WaitSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final AddressLayout WaitSemaphore$layout() {
        return WaitSemaphore$LAYOUT;
    }

    private static final long WaitSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("WaitSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final long WaitSemaphore$offset() {
        return WaitSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static MemorySegment WaitSemaphore(MemorySegment struct) {
        return struct.get(WaitSemaphore$LAYOUT, WaitSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static void WaitSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(WaitSemaphore$LAYOUT, WaitSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public final static class SignalSemaphore {

        private SignalSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(SignalSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SignalSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SignalSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SignalSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final AddressLayout SignalSemaphore$layout() {
        return SignalSemaphore$LAYOUT;
    }

    private static final long SignalSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("SignalSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final long SignalSemaphore$offset() {
        return SignalSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static MemorySegment SignalSemaphore(MemorySegment struct) {
        return struct.get(SignalSemaphore$LAYOUT, SignalSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporterImpl *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static void SignalSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SignalSemaphore$LAYOUT, SignalSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*Release)(OrtExternalResourceImporterImpl *)
     * }
     */
    public final static class Release {

        private Release() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(Release.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Release.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*Release)(OrtExternalResourceImporterImpl *)
     * }
     */
    public static final AddressLayout Release$layout() {
        return Release$LAYOUT;
    }

    private static final long Release$OFFSET = $LAYOUT.byteOffset(groupElement("Release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*Release)(OrtExternalResourceImporterImpl *)
     * }
     */
    public static final long Release$offset() {
        return Release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*Release)(OrtExternalResourceImporterImpl *)
     * }
     */
    public static MemorySegment Release(MemorySegment struct) {
        return struct.get(Release$LAYOUT, Release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*Release)(OrtExternalResourceImporterImpl *)
     * }
     */
    public static void Release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Release$LAYOUT, Release$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

