// Generated by jextract

package oracle.code.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtExternalTensorDescriptor {
 *     uint32_t version;
 *     ONNXTensorElementDataType element_type;
 *     const int64_t *shape;
 *     size_t rank;
 *     size_t offset_bytes;
 * }
 * }
 */
public class OrtExternalTensorDescriptor {

    OrtExternalTensorDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("version"),
        onnxruntime_c_api_h.C_INT.withName("element_type"),
        onnxruntime_c_api_h.C_POINTER.withName("shape"),
        onnxruntime_c_api_h.C_LONG.withName("rank"),
        onnxruntime_c_api_h.C_LONG.withName("offset_bytes")
    ).withName("OrtExternalTensorDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t version
     * }
     */
    public static final OfInt version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t version
     * }
     */
    public static int version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t version
     * }
     */
    public static void version(MemorySegment struct, int fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfInt element_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("element_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ONNXTensorElementDataType element_type
     * }
     */
    public static final OfInt element_type$layout() {
        return element_type$LAYOUT;
    }

    private static final long element_type$OFFSET = $LAYOUT.byteOffset(groupElement("element_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ONNXTensorElementDataType element_type
     * }
     */
    public static final long element_type$offset() {
        return element_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ONNXTensorElementDataType element_type
     * }
     */
    public static int element_type(MemorySegment struct) {
        return struct.get(element_type$LAYOUT, element_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ONNXTensorElementDataType element_type
     * }
     */
    public static void element_type(MemorySegment struct, int fieldValue) {
        struct.set(element_type$LAYOUT, element_type$OFFSET, fieldValue);
    }

    private static final AddressLayout shape$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("shape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int64_t *shape
     * }
     */
    public static final AddressLayout shape$layout() {
        return shape$LAYOUT;
    }

    private static final long shape$OFFSET = $LAYOUT.byteOffset(groupElement("shape"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int64_t *shape
     * }
     */
    public static final long shape$offset() {
        return shape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int64_t *shape
     * }
     */
    public static MemorySegment shape(MemorySegment struct) {
        return struct.get(shape$LAYOUT, shape$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int64_t *shape
     * }
     */
    public static void shape(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(shape$LAYOUT, shape$OFFSET, fieldValue);
    }

    private static final OfLong rank$LAYOUT = (OfLong)$LAYOUT.select(groupElement("rank"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t rank
     * }
     */
    public static final OfLong rank$layout() {
        return rank$LAYOUT;
    }

    private static final long rank$OFFSET = $LAYOUT.byteOffset(groupElement("rank"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t rank
     * }
     */
    public static final long rank$offset() {
        return rank$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t rank
     * }
     */
    public static long rank(MemorySegment struct) {
        return struct.get(rank$LAYOUT, rank$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t rank
     * }
     */
    public static void rank(MemorySegment struct, long fieldValue) {
        struct.set(rank$LAYOUT, rank$OFFSET, fieldValue);
    }

    private static final OfLong offset_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("offset_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t offset_bytes
     * }
     */
    public static final OfLong offset_bytes$layout() {
        return offset_bytes$LAYOUT;
    }

    private static final long offset_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("offset_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t offset_bytes
     * }
     */
    public static final long offset_bytes$offset() {
        return offset_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t offset_bytes
     * }
     */
    public static long offset_bytes(MemorySegment struct) {
        return struct.get(offset_bytes$LAYOUT, offset_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t offset_bytes
     * }
     */
    public static void offset_bytes(MemorySegment struct, long fieldValue) {
        struct.set(offset_bytes$LAYOUT, offset_bytes$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

