// Generated by jextract

package oracle.code.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtInteropApi {
 *     OrtStatusPtr (*CreateExternalResourceImporterForDevice)(const OrtEpDevice *, OrtExternalResourceImporter **);
 *     void (*ReleaseExternalResourceImporter)(OrtExternalResourceImporter *);
 *     OrtStatusPtr (*CanImportMemory)(const OrtExternalResourceImporter *, OrtExternalMemoryHandleType, bool *);
 *     OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **);
 *     void (*ReleaseExternalMemoryHandle)(OrtExternalMemoryHandle *);
 *     OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **);
 *     OrtStatusPtr (*CanImportSemaphore)(const OrtExternalResourceImporter *, OrtExternalSemaphoreType, bool *);
 *     OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporter *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **);
 *     void (*ReleaseExternalSemaphoreHandle)(OrtExternalSemaphoreHandle *);
 *     OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t);
 *     OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t);
 *     OrtStatusPtr (*InitGraphicsInteropForEpDevice)(const OrtEpDevice *, const OrtGraphicsInteropConfig *);
 *     OrtStatusPtr (*DeinitGraphicsInteropForEpDevice)(const OrtEpDevice *);
 * }
 * }
 */
public class OrtInteropApi {

    OrtInteropApi() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_POINTER.withName("CreateExternalResourceImporterForDevice"),
        onnxruntime_c_api_h.C_POINTER.withName("ReleaseExternalResourceImporter"),
        onnxruntime_c_api_h.C_POINTER.withName("CanImportMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("ImportMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("ReleaseExternalMemoryHandle"),
        onnxruntime_c_api_h.C_POINTER.withName("CreateTensorFromMemory"),
        onnxruntime_c_api_h.C_POINTER.withName("CanImportSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("ImportSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("ReleaseExternalSemaphoreHandle"),
        onnxruntime_c_api_h.C_POINTER.withName("WaitSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("SignalSemaphore"),
        onnxruntime_c_api_h.C_POINTER.withName("InitGraphicsInteropForEpDevice"),
        onnxruntime_c_api_h.C_POINTER.withName("DeinitGraphicsInteropForEpDevice")
    ).withName("OrtInteropApi");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateExternalResourceImporterForDevice)(const OrtEpDevice *, OrtExternalResourceImporter **)
     * }
     */
    public final static class CreateExternalResourceImporterForDevice {

        private CreateExternalResourceImporterForDevice() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CreateExternalResourceImporterForDevice.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CreateExternalResourceImporterForDevice.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CreateExternalResourceImporterForDevice$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CreateExternalResourceImporterForDevice"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateExternalResourceImporterForDevice)(const OrtEpDevice *, OrtExternalResourceImporter **)
     * }
     */
    public static final AddressLayout CreateExternalResourceImporterForDevice$layout() {
        return CreateExternalResourceImporterForDevice$LAYOUT;
    }

    private static final long CreateExternalResourceImporterForDevice$OFFSET = $LAYOUT.byteOffset(groupElement("CreateExternalResourceImporterForDevice"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateExternalResourceImporterForDevice)(const OrtEpDevice *, OrtExternalResourceImporter **)
     * }
     */
    public static final long CreateExternalResourceImporterForDevice$offset() {
        return CreateExternalResourceImporterForDevice$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateExternalResourceImporterForDevice)(const OrtEpDevice *, OrtExternalResourceImporter **)
     * }
     */
    public static MemorySegment CreateExternalResourceImporterForDevice(MemorySegment struct) {
        return struct.get(CreateExternalResourceImporterForDevice$LAYOUT, CreateExternalResourceImporterForDevice$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateExternalResourceImporterForDevice)(const OrtEpDevice *, OrtExternalResourceImporter **)
     * }
     */
    public static void CreateExternalResourceImporterForDevice(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CreateExternalResourceImporterForDevice$LAYOUT, CreateExternalResourceImporterForDevice$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*ReleaseExternalResourceImporter)(OrtExternalResourceImporter *)
     * }
     */
    public final static class ReleaseExternalResourceImporter {

        private ReleaseExternalResourceImporter() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ReleaseExternalResourceImporter.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ReleaseExternalResourceImporter.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ReleaseExternalResourceImporter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ReleaseExternalResourceImporter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalResourceImporter)(OrtExternalResourceImporter *)
     * }
     */
    public static final AddressLayout ReleaseExternalResourceImporter$layout() {
        return ReleaseExternalResourceImporter$LAYOUT;
    }

    private static final long ReleaseExternalResourceImporter$OFFSET = $LAYOUT.byteOffset(groupElement("ReleaseExternalResourceImporter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalResourceImporter)(OrtExternalResourceImporter *)
     * }
     */
    public static final long ReleaseExternalResourceImporter$offset() {
        return ReleaseExternalResourceImporter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalResourceImporter)(OrtExternalResourceImporter *)
     * }
     */
    public static MemorySegment ReleaseExternalResourceImporter(MemorySegment struct) {
        return struct.get(ReleaseExternalResourceImporter$LAYOUT, ReleaseExternalResourceImporter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalResourceImporter)(OrtExternalResourceImporter *)
     * }
     */
    public static void ReleaseExternalResourceImporter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ReleaseExternalResourceImporter$LAYOUT, ReleaseExternalResourceImporter$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportMemory)(const OrtExternalResourceImporter *, OrtExternalMemoryHandleType, bool *)
     * }
     */
    public final static class CanImportMemory {

        private CanImportMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_INT,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CanImportMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CanImportMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CanImportMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CanImportMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportMemory)(const OrtExternalResourceImporter *, OrtExternalMemoryHandleType, bool *)
     * }
     */
    public static final AddressLayout CanImportMemory$layout() {
        return CanImportMemory$LAYOUT;
    }

    private static final long CanImportMemory$OFFSET = $LAYOUT.byteOffset(groupElement("CanImportMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportMemory)(const OrtExternalResourceImporter *, OrtExternalMemoryHandleType, bool *)
     * }
     */
    public static final long CanImportMemory$offset() {
        return CanImportMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportMemory)(const OrtExternalResourceImporter *, OrtExternalMemoryHandleType, bool *)
     * }
     */
    public static MemorySegment CanImportMemory(MemorySegment struct) {
        return struct.get(CanImportMemory$LAYOUT, CanImportMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportMemory)(const OrtExternalResourceImporter *, OrtExternalMemoryHandleType, bool *)
     * }
     */
    public static void CanImportMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CanImportMemory$LAYOUT, CanImportMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public final static class ImportMemory {

        private ImportMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ImportMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ImportMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ImportMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ImportMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static final AddressLayout ImportMemory$layout() {
        return ImportMemory$LAYOUT;
    }

    private static final long ImportMemory$OFFSET = $LAYOUT.byteOffset(groupElement("ImportMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static final long ImportMemory$offset() {
        return ImportMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static MemorySegment ImportMemory(MemorySegment struct) {
        return struct.get(ImportMemory$LAYOUT, ImportMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryDescriptor *, OrtExternalMemoryHandle **)
     * }
     */
    public static void ImportMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ImportMemory$LAYOUT, ImportMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*ReleaseExternalMemoryHandle)(OrtExternalMemoryHandle *)
     * }
     */
    public final static class ReleaseExternalMemoryHandle {

        private ReleaseExternalMemoryHandle() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ReleaseExternalMemoryHandle.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ReleaseExternalMemoryHandle.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ReleaseExternalMemoryHandle$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ReleaseExternalMemoryHandle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalMemoryHandle)(OrtExternalMemoryHandle *)
     * }
     */
    public static final AddressLayout ReleaseExternalMemoryHandle$layout() {
        return ReleaseExternalMemoryHandle$LAYOUT;
    }

    private static final long ReleaseExternalMemoryHandle$OFFSET = $LAYOUT.byteOffset(groupElement("ReleaseExternalMemoryHandle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalMemoryHandle)(OrtExternalMemoryHandle *)
     * }
     */
    public static final long ReleaseExternalMemoryHandle$offset() {
        return ReleaseExternalMemoryHandle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalMemoryHandle)(OrtExternalMemoryHandle *)
     * }
     */
    public static MemorySegment ReleaseExternalMemoryHandle(MemorySegment struct) {
        return struct.get(ReleaseExternalMemoryHandle$LAYOUT, ReleaseExternalMemoryHandle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalMemoryHandle)(OrtExternalMemoryHandle *)
     * }
     */
    public static void ReleaseExternalMemoryHandle(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ReleaseExternalMemoryHandle$LAYOUT, ReleaseExternalMemoryHandle$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public final static class CreateTensorFromMemory {

        private CreateTensorFromMemory() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CreateTensorFromMemory.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CreateTensorFromMemory.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CreateTensorFromMemory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CreateTensorFromMemory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static final AddressLayout CreateTensorFromMemory$layout() {
        return CreateTensorFromMemory$LAYOUT;
    }

    private static final long CreateTensorFromMemory$OFFSET = $LAYOUT.byteOffset(groupElement("CreateTensorFromMemory"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static final long CreateTensorFromMemory$offset() {
        return CreateTensorFromMemory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static MemorySegment CreateTensorFromMemory(MemorySegment struct) {
        return struct.get(CreateTensorFromMemory$LAYOUT, CreateTensorFromMemory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CreateTensorFromMemory)(OrtExternalResourceImporter *, const OrtExternalMemoryHandle *, const OrtExternalTensorDescriptor *, OrtValue **)
     * }
     */
    public static void CreateTensorFromMemory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CreateTensorFromMemory$LAYOUT, CreateTensorFromMemory$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportSemaphore)(const OrtExternalResourceImporter *, OrtExternalSemaphoreType, bool *)
     * }
     */
    public final static class CanImportSemaphore {

        private CanImportSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_INT,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CanImportSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CanImportSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CanImportSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CanImportSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportSemaphore)(const OrtExternalResourceImporter *, OrtExternalSemaphoreType, bool *)
     * }
     */
    public static final AddressLayout CanImportSemaphore$layout() {
        return CanImportSemaphore$LAYOUT;
    }

    private static final long CanImportSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("CanImportSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportSemaphore)(const OrtExternalResourceImporter *, OrtExternalSemaphoreType, bool *)
     * }
     */
    public static final long CanImportSemaphore$offset() {
        return CanImportSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportSemaphore)(const OrtExternalResourceImporter *, OrtExternalSemaphoreType, bool *)
     * }
     */
    public static MemorySegment CanImportSemaphore(MemorySegment struct) {
        return struct.get(CanImportSemaphore$LAYOUT, CanImportSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*CanImportSemaphore)(const OrtExternalResourceImporter *, OrtExternalSemaphoreType, bool *)
     * }
     */
    public static void CanImportSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CanImportSemaphore$LAYOUT, CanImportSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporter *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public final static class ImportSemaphore {

        private ImportSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ImportSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ImportSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ImportSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ImportSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporter *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static final AddressLayout ImportSemaphore$layout() {
        return ImportSemaphore$LAYOUT;
    }

    private static final long ImportSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("ImportSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporter *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static final long ImportSemaphore$offset() {
        return ImportSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporter *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static MemorySegment ImportSemaphore(MemorySegment struct) {
        return struct.get(ImportSemaphore$LAYOUT, ImportSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*ImportSemaphore)(OrtExternalResourceImporter *, const OrtExternalSemaphoreDescriptor *, OrtExternalSemaphoreHandle **)
     * }
     */
    public static void ImportSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ImportSemaphore$LAYOUT, ImportSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*ReleaseExternalSemaphoreHandle)(OrtExternalSemaphoreHandle *)
     * }
     */
    public final static class ReleaseExternalSemaphoreHandle {

        private ReleaseExternalSemaphoreHandle() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ReleaseExternalSemaphoreHandle.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ReleaseExternalSemaphoreHandle.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ReleaseExternalSemaphoreHandle$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ReleaseExternalSemaphoreHandle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalSemaphoreHandle)(OrtExternalSemaphoreHandle *)
     * }
     */
    public static final AddressLayout ReleaseExternalSemaphoreHandle$layout() {
        return ReleaseExternalSemaphoreHandle$LAYOUT;
    }

    private static final long ReleaseExternalSemaphoreHandle$OFFSET = $LAYOUT.byteOffset(groupElement("ReleaseExternalSemaphoreHandle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalSemaphoreHandle)(OrtExternalSemaphoreHandle *)
     * }
     */
    public static final long ReleaseExternalSemaphoreHandle$offset() {
        return ReleaseExternalSemaphoreHandle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalSemaphoreHandle)(OrtExternalSemaphoreHandle *)
     * }
     */
    public static MemorySegment ReleaseExternalSemaphoreHandle(MemorySegment struct) {
        return struct.get(ReleaseExternalSemaphoreHandle$LAYOUT, ReleaseExternalSemaphoreHandle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*ReleaseExternalSemaphoreHandle)(OrtExternalSemaphoreHandle *)
     * }
     */
    public static void ReleaseExternalSemaphoreHandle(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ReleaseExternalSemaphoreHandle$LAYOUT, ReleaseExternalSemaphoreHandle$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public final static class WaitSemaphore {

        private WaitSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(WaitSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(WaitSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout WaitSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("WaitSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final AddressLayout WaitSemaphore$layout() {
        return WaitSemaphore$LAYOUT;
    }

    private static final long WaitSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("WaitSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final long WaitSemaphore$offset() {
        return WaitSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static MemorySegment WaitSemaphore(MemorySegment struct) {
        return struct.get(WaitSemaphore$LAYOUT, WaitSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*WaitSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static void WaitSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(WaitSemaphore$LAYOUT, WaitSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public final static class SignalSemaphore {

        private SignalSemaphore() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(SignalSemaphore.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SignalSemaphore.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SignalSemaphore$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SignalSemaphore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final AddressLayout SignalSemaphore$layout() {
        return SignalSemaphore$LAYOUT;
    }

    private static final long SignalSemaphore$OFFSET = $LAYOUT.byteOffset(groupElement("SignalSemaphore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static final long SignalSemaphore$offset() {
        return SignalSemaphore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static MemorySegment SignalSemaphore(MemorySegment struct) {
        return struct.get(SignalSemaphore$LAYOUT, SignalSemaphore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*SignalSemaphore)(OrtExternalResourceImporter *, OrtExternalSemaphoreHandle *, OrtSyncStream *, uint64_t)
     * }
     */
    public static void SignalSemaphore(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SignalSemaphore$LAYOUT, SignalSemaphore$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*InitGraphicsInteropForEpDevice)(const OrtEpDevice *, const OrtGraphicsInteropConfig *)
     * }
     */
    public final static class InitGraphicsInteropForEpDevice {

        private InitGraphicsInteropForEpDevice() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(InitGraphicsInteropForEpDevice.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(InitGraphicsInteropForEpDevice.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout InitGraphicsInteropForEpDevice$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("InitGraphicsInteropForEpDevice"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*InitGraphicsInteropForEpDevice)(const OrtEpDevice *, const OrtGraphicsInteropConfig *)
     * }
     */
    public static final AddressLayout InitGraphicsInteropForEpDevice$layout() {
        return InitGraphicsInteropForEpDevice$LAYOUT;
    }

    private static final long InitGraphicsInteropForEpDevice$OFFSET = $LAYOUT.byteOffset(groupElement("InitGraphicsInteropForEpDevice"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*InitGraphicsInteropForEpDevice)(const OrtEpDevice *, const OrtGraphicsInteropConfig *)
     * }
     */
    public static final long InitGraphicsInteropForEpDevice$offset() {
        return InitGraphicsInteropForEpDevice$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*InitGraphicsInteropForEpDevice)(const OrtEpDevice *, const OrtGraphicsInteropConfig *)
     * }
     */
    public static MemorySegment InitGraphicsInteropForEpDevice(MemorySegment struct) {
        return struct.get(InitGraphicsInteropForEpDevice$LAYOUT, InitGraphicsInteropForEpDevice$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*InitGraphicsInteropForEpDevice)(const OrtEpDevice *, const OrtGraphicsInteropConfig *)
     * }
     */
    public static void InitGraphicsInteropForEpDevice(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(InitGraphicsInteropForEpDevice$LAYOUT, InitGraphicsInteropForEpDevice$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*DeinitGraphicsInteropForEpDevice)(const OrtEpDevice *)
     * }
     */
    public final static class DeinitGraphicsInteropForEpDevice {

        private DeinitGraphicsInteropForEpDevice() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(DeinitGraphicsInteropForEpDevice.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DeinitGraphicsInteropForEpDevice.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DeinitGraphicsInteropForEpDevice$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DeinitGraphicsInteropForEpDevice"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*DeinitGraphicsInteropForEpDevice)(const OrtEpDevice *)
     * }
     */
    public static final AddressLayout DeinitGraphicsInteropForEpDevice$layout() {
        return DeinitGraphicsInteropForEpDevice$LAYOUT;
    }

    private static final long DeinitGraphicsInteropForEpDevice$OFFSET = $LAYOUT.byteOffset(groupElement("DeinitGraphicsInteropForEpDevice"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*DeinitGraphicsInteropForEpDevice)(const OrtEpDevice *)
     * }
     */
    public static final long DeinitGraphicsInteropForEpDevice$offset() {
        return DeinitGraphicsInteropForEpDevice$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*DeinitGraphicsInteropForEpDevice)(const OrtEpDevice *)
     * }
     */
    public static MemorySegment DeinitGraphicsInteropForEpDevice(MemorySegment struct) {
        return struct.get(DeinitGraphicsInteropForEpDevice$LAYOUT, DeinitGraphicsInteropForEpDevice$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*DeinitGraphicsInteropForEpDevice)(const OrtEpDevice *)
     * }
     */
    public static void DeinitGraphicsInteropForEpDevice(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DeinitGraphicsInteropForEpDevice$LAYOUT, DeinitGraphicsInteropForEpDevice$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

