// Generated by jextract

package oracle.code.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtResourceCount {
 *     uint32_t kind;
 *     uint32_t reserved;
 *     union {
 *         uint64_t total_bytes;
 *         uint64_t reserved_words[6];
 *     } value;
 * }
 * }
 */
public class OrtResourceCount {

    OrtResourceCount() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("kind"),
        onnxruntime_c_api_h.C_INT.withName("reserved"),
        OrtResourceCount.value.layout().withName("value")
    ).withName("OrtResourceCount");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt kind$LAYOUT = (OfInt)$LAYOUT.select(groupElement("kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final OfInt kind$layout() {
        return kind$LAYOUT;
    }

    private static final long kind$OFFSET = $LAYOUT.byteOffset(groupElement("kind"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static final long kind$offset() {
        return kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static int kind(MemorySegment struct) {
        return struct.get(kind$LAYOUT, kind$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t kind
     * }
     */
    public static void kind(MemorySegment struct, int fieldValue) {
        struct.set(kind$LAYOUT, kind$OFFSET, fieldValue);
    }

    private static final OfInt reserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final OfInt reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = $LAYOUT.byteOffset(groupElement("reserved"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static int reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t reserved
     * }
     */
    public static void reserved(MemorySegment struct, int fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     uint64_t total_bytes;
     *     uint64_t reserved_words[6];
     * }
     * }
     */
    public static class value {

        value() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            onnxruntime_c_api_h.C_LONG_LONG.withName("total_bytes"),
            MemoryLayout.sequenceLayout(6, onnxruntime_c_api_h.C_LONG_LONG).withName("reserved_words")
        ).withName("$anon$983:3");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final OfLong total_bytes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("total_bytes"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * uint64_t total_bytes
         * }
         */
        public static final OfLong total_bytes$layout() {
            return total_bytes$LAYOUT;
        }

        private static final long total_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("total_bytes"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * uint64_t total_bytes
         * }
         */
        public static final long total_bytes$offset() {
            return total_bytes$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * uint64_t total_bytes
         * }
         */
        public static long total_bytes(MemorySegment union) {
            return union.get(total_bytes$LAYOUT, total_bytes$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * uint64_t total_bytes
         * }
         */
        public static void total_bytes(MemorySegment union, long fieldValue) {
            union.set(total_bytes$LAYOUT, total_bytes$OFFSET, fieldValue);
        }

        private static final SequenceLayout reserved_words$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reserved_words"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static final SequenceLayout reserved_words$layout() {
            return reserved_words$LAYOUT;
        }

        private static final long reserved_words$OFFSET = $LAYOUT.byteOffset(groupElement("reserved_words"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static final long reserved_words$offset() {
            return reserved_words$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static MemorySegment reserved_words(MemorySegment union) {
            return union.asSlice(reserved_words$OFFSET, reserved_words$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static void reserved_words(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, reserved_words$OFFSET, reserved_words$LAYOUT.byteSize());
        }

        private static long[] reserved_words$DIMS = { 6 };

        /**
         * Dimensions for array field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static long[] reserved_words$dimensions() {
            return reserved_words$DIMS;
        }
        private static final VarHandle reserved_words$ELEM_HANDLE = reserved_words$LAYOUT.varHandle(sequenceElement());

        /**
         * Indexed getter for field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static long reserved_words(MemorySegment union, long index0) {
            return (long)reserved_words$ELEM_HANDLE.get(union, reserved_words$OFFSET, index0);
        }

        /**
         * Indexed setter for field:
         * {@snippet lang=c :
         * uint64_t reserved_words[6]
         * }
         */
        public static void reserved_words(MemorySegment union, long index0, long fieldValue) {
            reserved_words$ELEM_HANDLE.set(union, reserved_words$OFFSET, index0, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     uint64_t total_bytes;
     *     uint64_t reserved_words[6];
     * } value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     uint64_t total_bytes;
     *     uint64_t reserved_words[6];
     * } value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     uint64_t total_bytes;
     *     uint64_t reserved_words[6];
     * } value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     uint64_t total_bytes;
     *     uint64_t reserved_words[6];
     * } value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

