// Generated by jextract

package oracle.code.onnx.foreign;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtScanKernelHelper {
 *     uint32_t ort_version_supported;
 *     void (*Release)(OrtScanKernelHelper *);
 *     OrtStatusPtr (*Transpose)(OrtScanKernelHelper *, const size_t *, size_t, const OrtValue *, OrtSyncStream *, OrtValue *);
 * }
 * }
 */
public class OrtScanKernelHelper {

    OrtScanKernelHelper() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("ort_version_supported"),
        MemoryLayout.paddingLayout(4),
        onnxruntime_c_api_h.C_POINTER.withName("Release"),
        onnxruntime_c_api_h.C_POINTER.withName("Transpose")
    ).withName("OrtScanKernelHelper");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ort_version_supported$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ort_version_supported"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final OfInt ort_version_supported$layout() {
        return ort_version_supported$LAYOUT;
    }

    private static final long ort_version_supported$OFFSET = $LAYOUT.byteOffset(groupElement("ort_version_supported"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final long ort_version_supported$offset() {
        return ort_version_supported$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static int ort_version_supported(MemorySegment struct) {
        return struct.get(ort_version_supported$LAYOUT, ort_version_supported$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static void ort_version_supported(MemorySegment struct, int fieldValue) {
        struct.set(ort_version_supported$LAYOUT, ort_version_supported$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*Release)(OrtScanKernelHelper *)
     * }
     */
    public final static class Release {

        private Release() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(Release.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Release.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*Release)(OrtScanKernelHelper *)
     * }
     */
    public static final AddressLayout Release$layout() {
        return Release$LAYOUT;
    }

    private static final long Release$OFFSET = $LAYOUT.byteOffset(groupElement("Release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*Release)(OrtScanKernelHelper *)
     * }
     */
    public static final long Release$offset() {
        return Release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*Release)(OrtScanKernelHelper *)
     * }
     */
    public static MemorySegment Release(MemorySegment struct) {
        return struct.get(Release$LAYOUT, Release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*Release)(OrtScanKernelHelper *)
     * }
     */
    public static void Release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Release$LAYOUT, Release$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatusPtr (*Transpose)(OrtScanKernelHelper *, const size_t *, size_t, const OrtValue *, OrtSyncStream *, OrtValue *)
     * }
     */
    public final static class Transpose {

        private Transpose() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(Transpose.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Transpose.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Transpose$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Transpose"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*Transpose)(OrtScanKernelHelper *, const size_t *, size_t, const OrtValue *, OrtSyncStream *, OrtValue *)
     * }
     */
    public static final AddressLayout Transpose$layout() {
        return Transpose$LAYOUT;
    }

    private static final long Transpose$OFFSET = $LAYOUT.byteOffset(groupElement("Transpose"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*Transpose)(OrtScanKernelHelper *, const size_t *, size_t, const OrtValue *, OrtSyncStream *, OrtValue *)
     * }
     */
    public static final long Transpose$offset() {
        return Transpose$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*Transpose)(OrtScanKernelHelper *, const size_t *, size_t, const OrtValue *, OrtSyncStream *, OrtValue *)
     * }
     */
    public static MemorySegment Transpose(MemorySegment struct) {
        return struct.get(Transpose$LAYOUT, Transpose$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatusPtr (*Transpose)(OrtScanKernelHelper *, const size_t *, size_t, const OrtValue *, OrtSyncStream *, OrtValue *)
     * }
     */
    public static void Transpose(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Transpose$LAYOUT, Transpose$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

