/*
 * Copyright (c) 2024-2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package optkl.codebuilders;

import jdk.incubator.code.Op;
import jdk.incubator.code.dialect.core.CoreOp;
import jdk.incubator.code.dialect.java.JavaOp;
import optkl.util.Mutable;

import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.stream.Stream;

/**
 * Extends the base TextBuilder to add common constructs/keywords for generating C99/Java style code.
 *
 * @author Gary Frost
 */
public abstract class CodeBuilder<T extends CodeBuilder<T>>
        extends TextBuilder<T> implements CodeRenderer<T> {

    final public T semicolon() {
        return symbol(";");
    }

    final public T snl() {
        return semicolon().nl();
    }

    final public T cnl() {
        return comma().nl();
    }
    final public T comma() {
        return symbol(",");
    }

    final public T csp() {
        return comma().sp();
    }

    final  public T tilde() {
        return symbol("~");
    }

    final public T dot() {
        return symbol(".");
    }

    final public T leftShift() {
        return symbol("<<");
    }

    final public T rightShift() {
        return symbol(">>");
    }

    final public T rightShift(int v) {
        return rightShift().intValue(v);
    }

    final public T leftShift(int v) {
        return leftShift().intValue(v);
    }

    final public T equals() {
        return symbol("=");
    }

    final public T assign() {
        return sp().equals().sp();
    }

    final public T dollar() {
        return symbol("$");
    }

    final public T plusplus() {
        return symbol("++");
    }

    final public T plusEquals() {
        return symbol("+=");
    }

    final public T minusminus() {
        return symbol("--");
    }

    final public T ne() {
        return pling().equals();
    }

    final public T lineComment(String line) {
        return comment("//").sp().comment(line).nl();
    }

    final public T autoGenerated(){
        return nl().lineComment("Auto generated DO NOT EDIT").nl();
    }

    @Override
    final public T constant(String text) {
        return emitText(text);
    }

    public final T constantHalf(Integer value) {
        return emitText("(half)"+value);
    }


    final public T blockComment(String block) {
        return comment("/*").nl().comment(block).nl().symbol("*/").nl();
    }

    final public T blockInlineComment(String block) {
        return comment("/*").sp().comment(block).sp().comment("*/");
    }

    final public T newKeyword() {
        return keyword("new");
    }
    final public T newKwSp() {
        return newKeyword().sp();
    }

    final public T staticKeyword() {
        return keyword("static");
    }
    final public T staticKwSp() {
        return staticKeyword().sp();
    }

    final public T constexprKeyword() {
        return keyword("constexpr");
    }

    final public T constKeyword() {
        return keyword("const");
    }

    final public T explicitKeyword() {
        return keyword("explicit");
    }

    final public T virtualKeyword() {
        return keyword("virtual");
    }

    final public T ifKeyword() {
        return keyword("if");
    }

    final public T whileKeyword() {
        return keyword("while");
    }


    final public T breakKeyword() {
        return keyword("break");
    }

    final public T gotoKeyword() {
        return keyword("goto");
    }

    final public T continueKeyword() {
        return keyword("continue");
    }


    final public T colon() {
        return symbol(":");
    }


    final public T nullConst() {
        return symbol("NULL");
    }


    final public T elseKeyword() {
        return keyword("else");
    }


    final public T returnKeyword() {
        return keyword("return");
    }
    final public T returnKwSp() {
        return returnKeyword().sp();
    }

    final public T returnKeyword(String identifier) {
        return returnKeyword().sp().id(identifier);
    }

    final public T switchKeyword() {
        return keyword("switch");
    }


    final public T caseKeyword() {
        return keyword("case");
    }


    final public T defaultKeyword() {
        return keyword("default");
    }
    final public T defaultKwSp() {
        return defaultKeyword().sp();
    }

    final public T defaultKeyword( String typeName) {
        return defaultKeyword().sp().type(typeName);
    }

    final public T doKeyword() {
        return keyword("do");
    }

    final public T forKeyword() {
        return keyword("for");
    }

    final public T ampersand() {
        return symbol("&");
    }

    final public T addressOf(String identifier) {
        return ampersand().id(identifier);
    }

    final public T asterisk() {
        return symbol("*");
    }

    final public T dereference(String identifier) {
        return asterisk().id(identifier);
    }

    final public T mul() {
        return asterisk();
    }

    final public T percent() {
        return symbol("%");
    }

    final public T mod() {
        return percent();
    }

    final  public T slash() {
        return symbol("/");
    }

    final  public T div() {
        return slash();
    }

    final  public T plus() {
        return symbol("+");
    }

    final  public T add() {
        return plus();
    }

    final  public T minus() {
        return symbol("-");
    }

    final  public T sub() {
        return minus();
    }

    final  public T lt() {
        return symbol("<");
    }

    final  public T eq() {
        return equals().equals();
    }

    final  public T lte() {
        return lt().equals();
    }

    final  public T gte() {
        return gt().equals();
    }

    final   public T pling() {
        return symbol("!");
    }

    final   public T gt() {
        return symbol(">");
    }

    final  public T condAnd() {
        return symbol("&&");
    }

    final  public T condOr() {
        return symbol("||");
    }

    final  public T oparen() {
        return symbol("(");
    }

    final  public  T paren(Consumer<T> consumer) {
        return oparen().accept(consumer).cparen();
    }

    final  public T ocparen() {
        return oparen().cparen();
    }

    final  public T parenWhen(boolean value, Consumer<T> consumer) {
        if (value) {
            oparen().accept(consumer).cparen();
        } else {
            accept(consumer);
        }
        return self();
    }

    final  public T semicolonTerminated(Consumer<T> consumer) {
        return accept(consumer).semicolon();
    }

    final  public T semicolonNlTerminated(Consumer<T> consumer) {
        return semicolonTerminated(consumer).nl();
    }

    final  public T obrace() {
        return symbol("{");
    }

    final  public T indent(Consumer<T> ct) {
        return in().accept(ct).out();
    }

    final  public T nlIndentNl(Consumer<T> ct) {
        return nl().indent(ct).nl();
    }

    final  public T braceNlIndented(Consumer<T> ct) {
        return obrace().nlIndentNl(ct).cbrace();
    }

    final  public T parenNlIndented(Consumer<T> ct) {
        return oparen().nlIndentNl(ct).cparen();
    }

    final  public T brace(Consumer<T> ct) {
        return obrace().indent(ct).cbrace();
    }

    final  public T ocsbrace() {
        return osbrace().csbrace();
    }

    final   public T ocbrace() {
        return obrace().cbrace();
    }

    final  public T sbrace(Consumer<T> ct) {
        return osbrace().accept(ct).csbrace();
    }

    final   public T accept(Consumer<T> ct) {
        ct.accept(self());
        return self();
    }


    final   public T ochevron() {
        return rawochevron();
    }

    final public T rawochevron() {
        return emitText("<");
    }

    final   public T bitwiseOR() {
        return symbol("|");
    }

    final  public T cchevron() {
        return rawcchevron();
    }

    final  public T chevron(Consumer<T> ct) {
        return rawochevron().indent(ct).rawcchevron();
    }

     final public T rawcchevron() {
        return emitText(">");
    }

    final  public T osbrace() {
        return symbol("[");
    }

    final  public T cparen() {
        return symbol(")");
    }

    final  public T cbrace() {
        return symbol("}");
    }


    final  public T csbrace() {
        return symbol("]");
    }

    final  public T underscore() {
        return symbol("_");
    }

    final  public T dquote() {
        return symbol("\"");
    }

    final  public T odquote() {
        return dquote();
    }

    final  public T cdquote() {
        return dquote();
    }

    final  public T squote() {
        return symbol("'");
    }

    final  public T osquote() {
        return squote();
    }

    final  public T csquote() {
        return squote();
    }

    final   public T dquote(String string) {
        return odquote().escaped(string).cdquote();
    }

    final  public T at() {
        return symbol("@");
    }

    final   public T hat() {
        return symbol("^");
    }

    final  public T squote(String txt) {
        return osquote().escaped(txt).csquote();
    }

    final  public T rarrow() {
        return symbol("->");
    }

    final  public T larrow() {
        return symbol("<-");
    }


    final   public T questionMark() {
        return symbol("?");
    }

    final  public T hash() {
        return symbol("#");
    }

    final   public T when(boolean c, Consumer<T> consumer) {
        if (c) {
            accept(consumer);
        }
        return self();
    }

    final  public T either(boolean c, Consumer<T> lhs, Consumer<T> rhs) {
        if (c) {
            accept(lhs);
        } else {
            accept(rhs);
        }
        return self();
    }



    final   public <I> T sep(Iterable<I> iterable, Consumer<T> separator, Consumer<I> consumer) {
        var first = Mutable.of(true);
        iterable.forEach(t -> {
            if (first.get()) {
                first.set(false);
            } else {
                separator.accept(self());
            }
            consumer.accept(t);
        });
        return self();
    }
    final   public <I> T joinX2(Iterable<I> iterable1, Iterable<I> iterable2, Consumer<T> separator, BiConsumer<I,I> consumer) {
        return sep(iterable1,separator, $1 -> sep(iterable2,separator, $2 -> consumer.accept($1, $2)));
    }

    // Join is a better name lets delegate for a while then deprecate
   // public <I> T separated(Iterable<I> iterable, Consumer<T> separator, Consumer<I> consumer) {
     //   return join(iterable,separator,consumer);
   // }

    final   public <I> T commaSpaceSeparated(Iterable<I> iterable, Consumer<I> consumer) {
        return sep(iterable, _ -> csp(), consumer);
    }

    final   public T commaSpaceSeparated(Consumer<T>... consumers) {
        for (int i = 0; i < consumers.length; i++) {
            if (i > 0) {
                csp();
            }
            consumers[i].accept(self());
        }
        return self();
    }

    final   public T args(Consumer<T>... consumers) {
        return commaSpaceSeparated(consumers);
    }

    final   public <I> T commaSeparated(Iterable<I> iterable, Consumer<I> consumer) {
        return sep(iterable, _ -> comma(), consumer);
    }

    final   public <I> T commaNlSeparated(Iterable<I> iterable, Consumer<I> consumer) {
        return sep(iterable, _ -> comma().nl(), consumer);
    }

    final  public <I> T barSeparated(Iterable<I> iterable, Consumer<I> consumer) {
        return sep(iterable, _ -> bitwiseOR(), consumer);
    }

    final  public <I> T semicolonNlSeparated(Iterable<I> iterable, Consumer<I> consumer) {
        return sep(iterable, _ -> snl(), consumer);
    }


    final  public <I> T sep(Stream<I> stream, Consumer<T> separator, Consumer<I> consumer) {
        var first = Mutable.of(true);
        stream.forEach(t -> {
            if (first.get()) {
                first.set(false);
            } else {
                separator.accept(self());
            }
            consumer.accept(t);
        });
        return self();
    }

    final   public <I> T commaSpaceSeparated(Stream<I> stream, Consumer<I> consumer) {
        return sep(stream, _ -> csp(), consumer);
    }

    final  public <I> T nlSeparated(Stream<I> stream, Consumer<I> consumer) {
        return sep(stream, _ -> nl(), consumer);
    }

    final public T s32Type() {
        return type("int");
    }

    final public T s32Type(String identifier) {
        return s32Type().sp().id(identifier);
    }

    final public T boolConst(boolean b) {
        return constant(Boolean.toString(b));
    }

    final public T intConst(int i) {
        return constant(Integer.toString(i));
    }
    final public T intConstZero() {
        return intConst(0);
    }
    final public T intConstOne() {
        return intConst(1);
    }

    final public T intConstTwo() {
        return intConst(2);
    }
    final public T floatConst(float f) {
        return constant(f+"f");
    }
    final public T floatConstZero() {
        return floatConst(0f);
    }



    final public T voidType() {
        return type("void");
    }

    final public T s08Type() {
        return type("char");
    }

    final public T s08Type(String name) {
        return s08Type().sp().id(name);
    }

    final public T f32Type() {
        return type("float");
    }

    final public T f32Type(String identifier) {
        return f32Type().sp().id(identifier);
    }

    final public T s64Type() {
        return type("long");
    }

    final public T f64Type() {
        return type("double");
    }

    final public T boolType() {
        return type("char");
    }

    final public T s16Type() {
        return type("short");
    }

    final public T s16Type(String identifier) {
        return s16Type().sp().id(identifier);
    }


    @Override
    final public T comment(String text) {
        return emitText(text);
    }

    @Override
    final public T id(String text) {
        return emitText(text);
    }


    @Override
    final public T reserved(String text) {
        return emitText(text);
    }

    @Override
    final public T label(String text) {
        return emitText(text);
    }

    @Override
    final public T symbol(String text) {
        return emitText(text);
    }

    @Override
    final public T type(String text) {
        return emitText(text);
    }

    @Override
    final public T keyword(String text) {
        return emitText(text);
    }

    @Override
    final public T literal(String text) {
        return emitText(text);
    }

    final  public T nl(int n) {
        for (int i=0; i< n;i++){
            nl();
        }
       return self();
    }

    @Override
   final  public T sp() {
        return emitText(" ");
    }

   final  public String toCamelExceptFirst(String s) {
        String[] parts = s.split("_");
        StringBuilder camelCaseString = new StringBuilder();
        for (String part : parts) {
            camelCaseString.append(camelCaseString.isEmpty()
                    ? part.toLowerCase()
                    : part.substring(0, 1).toUpperCase() + part.substring(1).toLowerCase());
        }
        return camelCaseString.toString();
    }

    public T using() {
        return emitText("using");
    }

    public T namespace() {
        return emitText("namespace");
    }

    public T builtin(String text) {
        return emitText(text);
    }

    final public T oracleCopyright(){
        return blockComment("""
                * Copyright (c) 2025-2026, Oracle and/or its affiliates. All rights reserved.
                * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
                *
                * This code is free software; you can redistribute it and/or modify it
                * under the terms of the GNU General Public License version 2 only, as
                * published by the Free Software Foundation.  Oracle designates this
                * particular file as subject to the "Classpath" exception as provided
                * by Oracle in the LICENSE file that accompanied this code.
                *
                * This code is distributed in the hope that it will be useful, but WITHOUT
                * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
                * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
                * version 2 for more details (a copy is included in the LICENSE file that
                * accompanied this code).
                *
                * You should have received a copy of the GNU General Public License version
                * 2 along with this work; if not, write to the Free Software Foundation,
                * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
                *
                * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
                * or visit www.oracle.com if you need additional information or have any
                * questions."""
        );
    }
    final public T varName(String name) {
        return id(name);
    }

    final public T varName(CoreOp.VarOp varOp) {
        return varName(varOp.varName());
    }
    final public T varName(CoreOp.VarAccessOp.VarLoadOp varOp) {
        blockInlineComment(varOp.toString());
        return self();
    }
    final public  T funcName(CoreOp.FuncCallOp funcCallOp){
        return funcName(funcCallOp.funcName());
    }
    final public  T funcName(String name){
        return id(name);
    }
    final public T funcName(CoreOp.FuncOp funcOp) {
        return funcName(funcOp.funcName());
    }
    final public T fieldName(JavaOp.FieldAccessOp fieldAccessOp) {
        return id(fieldAccessOp.fieldReference().name());
    }
    final public T funcName(JavaOp.InvokeOp invokeOp){
        return id(invokeOp.invokeReference().name());
    }


    protected final T camel(String value) {
        return id(Character.toString(Character.toLowerCase(value.charAt(0)))).id(value.substring(1));
    }

    final public T camelJoin(String prefix, String suffix) {
        return camel(prefix).id(Character.toString(Character.toUpperCase(suffix.charAt(0)))).id(suffix.substring(1));
    }

    public T symbol(Op op) {
        return switch (op) {
            case JavaOp.ModOp o -> percent();
            case JavaOp.MulOp o -> mul();
            case JavaOp.DivOp o -> div();
            case JavaOp.AddOp o -> add();
            case JavaOp.SubOp o -> sub();
            case JavaOp.LtOp o -> lt();
            case JavaOp.GtOp o -> gt();
            case JavaOp.LeOp o -> lte();
            case JavaOp.GeOp o -> gte();
            case JavaOp.AshrOp o -> cchevron().cchevron();
            case JavaOp.LshlOp o -> ochevron().ochevron();
            case JavaOp.LshrOp o -> cchevron().cchevron();
            case JavaOp.NeqOp o -> pling().equals();
            case JavaOp.NegOp o -> minus();
            case JavaOp.EqOp o -> equals().equals();
            case JavaOp.NotOp o -> pling();
            case JavaOp.AndOp o -> ampersand();
            case JavaOp.OrOp o -> bitwiseOR();
            case JavaOp.XorOp o -> hat();
            case JavaOp.ConditionalAndOp o -> condAnd();
            case JavaOp.ConditionalOrOp o -> condOr();
            default -> throw new IllegalStateException("Unexpected value: " + op);
        };
    }
}
