import jdk.incubator.code.Reflect;
import jdk.incubator.code.Op;
import jdk.incubator.code.Quoted;
import jdk.incubator.code.dialect.core.CoreOp;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.util.List;
import java.util.Optional;
import java.util.function.IntUnaryOperator;
import java.util.stream.IntStream;
import java.util.stream.Stream;

/*
 * @test
 * @summary test that lambda model generated by the compiler is shared across instances of the same lambda class.
 * This property means we only invoke the op building method once per lambda class.
 * @modules jdk.incubator.code
 * @run junit TestLambdaModelUnique
 */
public class TestLambdaModelUnique {

    Runnable f() {
        return (@Reflect Runnable) () -> {
            System.out.println("Running...");
        };
    }

    @Test
    public void testWithLambdaThatDoNotCaptureInSequence() {
        Runnable q1 = f();
        Runnable q2 = f();
        Quoted quoted1 = Op.ofQuotable(q1).orElseThrow();
        Quoted quoted2 = Op.ofQuotable(q2).orElseThrow();
        Assertions.assertSame(quoted1.op(), quoted2.op());
    }

    @Test
    public void testWithLambdaThatDoNotCaptureInParallel() { // parallel
        Runnable q1 = f();
        Runnable q2 = f();
        List<Op> ops = Stream.of(q1, q2).parallel().map(q -> Op.ofQuotable(q).orElseThrow().op()).toList();
        Assertions.assertSame(ops.getFirst(), ops.getLast());
    }

    static IntUnaryOperator g(int i) {
        return (@Reflect IntUnaryOperator) j -> j + i;
    }

    @Test
    public void testWithLambdaThatCaptureInSequence() {
        IntUnaryOperator q1 = g(1);
        IntUnaryOperator q2 = g(2);
        Quoted quoted1 = Op.ofQuotable(q1).orElseThrow();
        Quoted quoted2 = Op.ofQuotable(q2).orElseThrow();
        Assertions.assertSame(quoted1.op(), quoted2.op());
    }

    @Test
    public void testWithLambdaThatCaptureInParallel() {
        IntUnaryOperator q1 = g(1);
        IntUnaryOperator q2 = g(2);
        List<Op> ops = Stream.of(q1, q2).parallel().map(q -> Op.ofQuotable(q).orElseThrow().op()).toList();
        Assertions.assertSame(ops.getFirst(), ops.getLast());
    }
}
