// Generated by jextract

package oracle.code.onnx.foreign.coreml;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct __arm_pagein_state {
 *     int __pagein_error;
 * }
 * }
 */
public class __arm_pagein_state {

    __arm_pagein_state() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        coreml_provider_factory_h.C_INT.withName("__pagein_error")
    ).withName("__arm_pagein_state");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt __pagein_error$LAYOUT = (OfInt)$LAYOUT.select(groupElement("__pagein_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int __pagein_error
     * }
     */
    public static final OfInt __pagein_error$layout() {
        return __pagein_error$LAYOUT;
    }

    private static final long __pagein_error$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int __pagein_error
     * }
     */
    public static final long __pagein_error$offset() {
        return __pagein_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int __pagein_error
     * }
     */
    public static int __pagein_error(MemorySegment struct) {
        return struct.get(__pagein_error$LAYOUT, __pagein_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int __pagein_error
     * }
     */
    public static void __pagein_error(MemorySegment struct, int fieldValue) {
        struct.set(__pagein_error$LAYOUT, __pagein_error$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

