// Generated by jextract

package oracle.code.onnx.foreign.coreml;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct __darwin_arm_sme_za_state {
 *     char __za[4096];
 * }
 * }
 */
public class __darwin_arm_sme_za_state {

    __darwin_arm_sme_za_state() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(4096, coreml_provider_factory_h.C_CHAR).withName("__za")
    ).withName("__darwin_arm_sme_za_state");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout __za$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("__za"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static final SequenceLayout __za$layout() {
        return __za$LAYOUT;
    }

    private static final long __za$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static final long __za$offset() {
        return __za$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static MemorySegment __za(MemorySegment struct) {
        return struct.asSlice(__za$OFFSET, __za$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static void __za(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, __za$OFFSET, __za$LAYOUT.byteSize());
    }

    private static long[] __za$DIMS = { 4096 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static long[] __za$dimensions() {
        return __za$DIMS;
    }
    private static final VarHandle __za$ELEM_HANDLE = __za$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static byte __za(MemorySegment struct, long index0) {
        return (byte)__za$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char __za[4096]
     * }
     */
    public static void __za(MemorySegment struct, long index0, byte fieldValue) {
        __za$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

